In [46]:
import pandas as pd
import numpy as np
import csv

In [47]:
"""
All constants defined here, and we only need to modify here in the future, hopefully.
"""


# A
FILE_PATH = "2-18-07pkg20.csv"
# OUTPUT_PATH = "../processed/2-18-07pkg20_del.csv"

# B
# We want id, roadDist, value
# which are in col index 2,4,16
index_to_keep = [2,4,16]
PATTERN = 21  # number of entries of one road line, which form a pattern
col_of_one = ["id", "roadDist", "value"]

PLACE_HOLDER = -99.99

In [48]:
with open(FILE_PATH, 'r', encoding="utf-8") as csvfile:
    reader = csv.reader(csvfile)
    MAX_LEN = max(len(_) for _ in reader)
    
MAX_LEN

87

In [50]:
original_col_names = ["temp.{}".format(i) for i in range(MAX_LEN)]
df = pd.read_csv(FILE_PATH, names=original_col_names)
df

,temp.0,temp.1,temp.2,temp.3,temp.4,temp.5,temp.6,temp.7,temp.8,temp.9,...,temp.77,temp.78,temp.79,temp.80,temp.81,temp.82,temp.83,temp.84,temp.85,temp.86
0,simTime,simFrame,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,+1.0000000000000000e-02,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,+2.0000000000000000e-02,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,+2.9999999999999999e-02,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,+4.0000000000000001e-02,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4660,+4.6599999999999298e+01,4661,24.0,1.0,12.655337,324.385213,1.096151,0.0,-0.002804,1.490116e-08,...,274.0,55.0,50.0,0.0,1.0,0.0,0.0,-99.0,99.0,NaN
4661,+4.6609999999999296e+01,4662,24.0,1.0,12.737603,324.385213,1.096151,0.0,-0.002804,1.490116e-08,...,274.0,55.0,50.0,0.0,1.0,0.0,0.0,-99.0,99.0,NaN
4662,+4.6619999999999294e+01,4663,24.0,1.0,12.819881,324.385213,1.096151,0.0,-0.002804,1.490116e-08,...,274.0,55.0,50.0,0.0,1.0,0.0,0.0,-99.0,99.0,NaN
4663,+4.6629999999999292e+01,4664,24.0,1.0,12.902172,324.385213,1.096151,0.0,-0.002804,1.490116e-08,...,274.0,55.0,50.0,0.0,1.0,0.0,0.0,-99.0,99.0,NaN
4664,+4.6639999999999290e+01,4665,24.0,1.0,12.984475,324.385213,1.096151,0.0,-0.002804,1.490116e-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
original_col_names = ["temp.{}".format(i) for i in range(MAX_LEN)]
df = pd.DataFrame(columns=original_col_names)

with open(FILE_PATH, 'r', encoding="utf-8") as csvfile:
    reader = csv.reader(csvfile)
    for i, row in enumerate(reader):
        length = len(row)
        std_row = row + ['']*(MAX_LEN-length)
        df.loc[i] = std_row
        

df.drop(index=0, axis=0, inplace=True)
df.index -= 1        
      
df

,temp.0,temp.1,temp.2,temp.3,temp.4,temp.5,temp.6,temp.7,temp.8,temp.9,...,temp.77,temp.78,temp.79,temp.80,temp.81,temp.82,temp.83,temp.84,temp.85,temp.86
0,+1.0000000000000000e-02,2,,,,,,,,,...,,,,,,,,,,
1,+2.0000000000000000e-02,3,,,,,,,,,...,,,,,,,,,,
2,+2.9999999999999999e-02,4,,,,,,,,,...,,,,,,,,,,
3,+4.0000000000000001e-02,5,,,,,,,,,...,,,,,,,,,,
4,+5.0000000000000003e-02,6,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4659,+4.6599999999999298e+01,4661,24,1,+1.2655337333679199e+01,+3.2438521348525916e+02,+1.0961511293566972e+00,+0.0000000000000000e+00,-2.8035880532115698e-03,+1.4901161193847656e-08,...,274,55,+5.0000000000000000e+01,0,1,0,0,-99,99,
4660,+4.6609999999999296e+01,4662,24,1,+1.2737603187561035e+01,+3.2438521348525916e+02,+1.0961511293566972e+00,+0.0000000000000000e+00,-2.8035880532115698e-03,+1.4901161193847656e-08,...,274,55,+5.0000000000000000e+01,0,1,0,0,-99,99,
4661,+4.6619999999999294e+01,4663,24,1,+1.2819881439208984e+01,+3.2438521348525916e+02,+1.0961511293566972e+00,+0.0000000000000000e+00,-2.8035880532115698e-03,+1.4901161193847656e-08,...,274,55,+5.0000000000000000e+01,0,1,0,0,-99,99,
4662,+4.6629999999999292e+01,4664,24,1,+1.2902172088623047e+01,+3.2438521348525916e+02,+1.0961511293566972e+00,+0.0000000000000000e+00,-2.8035880532115698e-03,+1.4901161193847656e-08,...,274,55,+5.0000000000000000e+01,0,1,0,0,-99,99,
4663,+4.6639999999999290e+01,4665,24,1,+1.2984475135803223e+01,+3.2438521348525916e+02,+1.0961511293566972e+00,+0.0000000000000000e+00,-2.8035880532115698e-03,+1.4901161193847656e-08,...,,,,,,,,,,