In [1]:
"""
This file should handle the raw csv of pkg7 produced by VTD
"""
import pandas as pd
import numpy as np
import csv

In [14]:
"""
All constants defined here, and we only need to modify here in the future, hopefully.
"""


# A
DATA_DIR = "../raw_data/0810/0810_2_24/"
SCENE = "2_24"
PKG_ID = '9'
FILE_PATH = DATA_DIR + SCENE + "pkg{}.csv".format(PKG_ID)

OUT_DIR = "../processed/processed_0810/"
OUTPUT_PATH = OUT_DIR+SCENE+"pkg{}_del.csv".format(PKG_ID)

# B
"""
# We want objectId, X, Y, yaw_angle(h after X), Vx, Vy, Ax, Ay as well as dimXYZ, offXYZ for all cars
# col index see below (*range(7,13) is 7~12, dimXYZ and offXYZ)
"""
index_to_keep = [2, 4, *range(7,13), 13, 14, 16, 22, 23, 31, 32] # remainder of index//PATTERN
PATTERN = 39  # number of entries of one road line, which form a pattern
col_of_one = ["objectId", 'obj_type','dimX','dimY','dimZ','offX','offY','offZ', "X", "Y", "yaw_angle", "Vx","Vy", "Ax", "Ay"]


PLACE_HOLDER = -99.99

In [15]:
with open(FILE_PATH, 'r', encoding="utf-8") as csvfile:
    reader = csv.reader(csvfile)
    MAX_LEN = max(len(_) for _ in reader)
    
MAX_LEN

160

In [16]:
original_col_names = ["temp.{}".format(i) for i in range(MAX_LEN)]
df9 = pd.read_csv(FILE_PATH, names=original_col_names, low_memory=False)        

df9.drop(index=0, axis=0, inplace=True)
df9.index -= 1 
df9.columns = [name.strip() for name in df9.columns]
      
df9.tail(10)

,temp.0,temp.1,temp.2,temp.3,temp.4,temp.5,temp.6,temp.7,temp.8,temp.9,...,temp.150,temp.151,temp.152,temp.153,temp.154,temp.155,temp.156,temp.157,temp.158,temp.159
4882,+4.8829998908564448e+01,4884,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4883,+4.8839998908340931e+01,4885,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4884,+4.8849998908117414e+01,4886,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4885,+4.8859998907893896e+01,4887,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4886,+4.8869998907670379e+01,4888,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4887,+4.8879998907446861e+01,4889,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4888,+4.8889998907223344e+01,4890,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4889,+4.8899998906999826e+01,4891,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4890,+4.8909998906776309e+01,4892,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4891,+4.8919998906552792e+01,4893,+2,1,1,0x7,FO,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
rows = df9.shape[0]
num_del = rows%100
df9.drop(labels=range(rows-num_del, rows), axis=0, inplace=True)
df9.shape

(4800, 160)

In [18]:
"""
Other constants which must be defined after reading in df.


Note: when determing number of objs, we use (#cols-2)/PATTERN.
    But quite often, the raw data has an empty column in the end,
    with pandas automatically giving a name "Unnamed.0"
"""
# C
while (len(df9.columns)-2)%PATTERN != 0:
    # del that col
    print("Found an empty col at the end")
    df9.drop(df9.columns[-1], axis=1, inplace=True)
    
NUM_OBJS = (len(df9.columns)-2)//PATTERN
BEGIN_IDX = NUM_OBJS # current df has 10 roadlines, 0-9
TARGET = 10 # we want 14
END_IDX = 10

# Check if it is a whole number
NUM_OBJS

Found an empty col at the end
Found an empty col at the end

4

In [19]:
"""### Keep those cols we want and check ###"""

# a list of column names to delete
cols_to_del = [name for i, name in enumerate(df9.columns) if i%PATTERN not in index_to_keep and i!=1]
df9 = df9.drop(columns=cols_to_del)
df9.head(10)

,temp.1,temp.2,temp.4,temp.7,temp.8,temp.9,temp.10,temp.11,temp.12,temp.13,...,temp.127,temp.128,temp.129,temp.130,temp.131,temp.133,temp.139,temp.140,temp.148,temp.149
0,2,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376218379009657e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
1,3,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376368378427962e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
2,4,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376618377458477e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
3,5,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376968376101210e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
4,6,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2377418374356175e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
5,7,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2377968372223393e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
6,8,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2378618369702878e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
7,9,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2379368366794644e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
8,10,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2380218363498720e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN
9,11,+2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2381168359815135e+01,...,+0.0000000000000000e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+6.8376832473271335e+01,+1.4549148834080761e-02,-4.5266817323863506e-03,NaN,NaN,NaN,NaN

In [20]:
"""### do some simple pre-process and check ###"""
df9.fillna(PLACE_HOLDER, inplace=True)
df9.rename(columns={"temp.1":"simFrame"}, inplace=True)
df9["simFrame"] = df9["simFrame"].astype(np.int64)
df9.set_index("simFrame", inplace=True)
df9 = df9[~df9.index.duplicated(keep='first')]

"""
# rename col names of first chunk: id to id.0
rename_dict = {name:name+'.0' for name in col_of_one}
df9.rename(columns=rename_dict, inplace=True)

# rename type.x to obj_type.x to distinguish (pkg 7 roadmark also has type)
type_dict = {"type.{}".format(i): "obj_type.{}".format(i) for i in range(NUM_OBJS)}
df9.rename(columns=type_dict, inplace=True)
"""

new_names = ["{}.{}".format(name,i) for i in range(NUM_OBJS) for name in col_of_one]
df9.columns = new_names

for i in range(NUM_OBJS):
    df9["{}.{}".format(col_of_one[0], i)] = df9["{}.{}".format(col_of_one[0], i)].apply(lambda x: int(x.strip()) if type(x)==str else x)
    print( df9["{}.{}".format(col_of_one[0], i)].value_counts())
    
# append empty colunms to match designated number of lines reserved: 14
"""
Idea explained in pkg 7 file
"""
for i in range(BEGIN_IDX, END_IDX):
    for name in col_of_one:
        df9[name+'.'+str(i)] = PLACE_HOLDER
        
        
NUM_OBJS = END_IDX

print(df9.shape)
df9.head(10)

2    4800
Name: objectId.0, dtype: int64
3    4800
Name: objectId.1, dtype: int64
1    4800
Name: objectId.2, dtype: int64
38    3684
39    1116
Name: objectId.3, dtype: int64
(4800, 150)

,objectId.0,obj_type.0,dimX.0,dimY.0,dimZ.0,offX.0,offY.0,offZ.0,X.0,Y.0,...,offX.9,offY.9,offZ.9,X.9,Y.9,yaw_angle.9,Vx.9,Vy.9,Ax.9,Ay.9
simFrame,,,,,,,,,,,,,,,,,,,,,
2,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376218379009657e+01,-8.4897430492969939e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
3,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376368378427962e+01,-8.4897845820845363e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
4,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376618377458477e+01,-8.4898538030844989e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
5,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2376968376101210e+01,-8.4899507119314210e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
6,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2377418374356175e+01,-8.4900753081647060e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
7,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2377968372223393e+01,-8.4902275912287606e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
8,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2378618369702878e+01,-8.4904075604731552e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
9,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2379368366794644e+01,-8.4906152151528164e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
10,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2380218363498720e+01,-8.4908505544282448e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
11,2,1,+4.8660001754760742e+00,+1.8420000076293945e+00,+1.4559999704360962e+00,+1.3070000410079956e+00,+0.0000000000000000e+00,+0.0000000000000000e+00,+5.2381168359815135e+01,-8.4911135773657609e-02,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99

In [21]:
"""
MOST important task: Standardization.

In many scenarios, not all objects will stay in the scene and recorded by the sensor, 
which results in mis-aligned chunks of cols for each object. For example
id0 id1 id2 id3
1   2   3   4
2   4   NaN NaN
............

TODO:
A sorting algorithm based on selection sort

Idea:
for each list(row):
    for each entry where objectId will be in, (a fixed jump of 14 here):
        group them and put into the place in the new list
        
    populate remaining entries, where the corresponding id is not in our data, with [NaN]*14
    new_list looks like [[data of id1], [data of id2], ......]
    flat the list
    list(row) = new_list
    
    
!!! Take quite a long time
"""
row_nums = df9.shape[0]    # 8336 this time
jump = len(col_of_one)   # 14

for row in range(row_nums):
    old_row = df9.iloc[row]
    new_row = [ [PLACE_HOLDER]*jump ]*NUM_OBJS


    for idx in range(0, 0 + NUM_OBJS*jump, jump):   # 0, 14, 28, ...
        objId = old_row[idx]
        if objId == PLACE_HOLDER or objId >= NUM_OBJS or objId <= 0:
            # Special case where id is placeholder -99.99 (also those trailing data)
            continue
        else:
            objId = int(objId)
            # ego car id=1 should go to objectId_0, id=5 should go to objectId=4 likewise.
            new_row[objId] = old_row[idx:idx+jump]
            
    # flat the list
    new_row = [item for sublist in new_row for item in sublist]
    df9.iloc[row] = new_row

              
df9.head(10)

,objectId.0,obj_type.0,dimX.0,dimY.0,dimZ.0,offX.0,offY.0,offZ.0,X.0,Y.0,...,offX.9,offY.9,offZ.9,X.9,Y.9,yaw_angle.9,Vx.9,Vy.9,Ax.9,Ay.9
simFrame,,,,,,,,,,,,,,,,,,,,,
2,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
3,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
4,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
5,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
6,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
7,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
8,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
9,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
10,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99
11,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,...,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99

In [22]:
for i in range(NUM_OBJS):
    print( df9["{}.{}".format(col_of_one[0], i)].value_counts())

-99.99    4800
Name: objectId.0, dtype: int64
1.0    4800
Name: objectId.1, dtype: int64
2.0    4800
Name: objectId.2, dtype: int64
3.0    4800
Name: objectId.3, dtype: int64
-99.99    4800
Name: objectId.4, dtype: int64
-99.99    4800
Name: objectId.5, dtype: int64
-99.99    4800
Name: objectId.6, dtype: int64
-99.99    4800
Name: objectId.7, dtype: int64
-99.99    4800
Name: objectId.8, dtype: int64
-99.99    4800
Name: objectId.9, dtype: int64

In [23]:
# do the check after the sort, there should be no output if it's correct
for i in range(END_IDX):
    assert len(df9["{}.{}".format(col_of_one[0], i)].value_counts()) <= 2, "objectId.{} col still has mixed id, need to further enlarge TARGET {}".format(i, TARGET)

In [24]:
new_names = ["{}_{}".format(name,i) for i in range(NUM_OBJS) for name in col_of_one]
df9.columns = new_names 
df9.columns

Index(['objectId_0', 'obj_type_0', 'dimX_0', 'dimY_0', 'dimZ_0', 'offX_0',
       'offY_0', 'offZ_0', 'X_0', 'Y_0',
       ...
       'offX_9', 'offY_9', 'offZ_9', 'X_9', 'Y_9', 'yaw_angle_9', 'Vx_9',
       'Vy_9', 'Ax_9', 'Ay_9'],
      dtype='object', length=150)

In [25]:
df9.to_csv(OUTPUT_PATH)