In [1]:
"""
This file should handle the raw csv of pkg7 produced by VTD
"""
import pandas as pd
import numpy as np
import csv

In [2]:
"""
All constants defined here, and we only need to modify here in the future, hopefully.
"""


# A
DATA_DIR = "../0809/2_24/"
SCENE = "2_24"
PKG_ID = '20'
FILE_PATH = DATA_DIR + SCENE + "pkg{}.csv".format(PKG_ID)

OUT_DIR = "../processed0809/"
OUTPUT_PATH = OUT_DIR+SCENE+"pkg{}_del.csv".format(PKG_ID)

# B
# We want id, roadDist, value
# which are in col index 2,4,16
index_to_keep = [2,4,16]
PATTERN = 21  # number of entries of one road line, which form a pattern
col_of_one = ["signId", "roadDist", "value"]


# C
BEGIN_IDX = 0+1 # current df has 7 roadlines, 0-6
END_IDX = 14 # we want 14
PLACE_HOLDER = -99.99

In [3]:
with open(FILE_PATH, 'r', encoding="utf-8") as csvfile:
    reader = csv.reader(csvfile)
    MAX_LEN = max(len(_) for _ in reader)
    
MAX_LEN

45

In [4]:
original_col_names = ["temp.{}".format(i) for i in range(MAX_LEN)]
df20 = pd.read_csv(FILE_PATH, names=original_col_names, low_memory=False)        

df20.drop(index=0, axis=0, inplace=True)
df20.index -= 1        
      
df20.tail(10)

,temp.0,temp.1,temp.2,temp.3,temp.4,temp.5,temp.6,temp.7,temp.8,temp.9,...,temp.35,temp.36,temp.37,temp.38,temp.39,temp.40,temp.41,temp.42,temp.43,temp.44
5816,+5.8169998699799180e+01,5818,39,1,+5.9955657958984375e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5817,+5.8179998699575663e+01,5819,39,1,+6.0086238861083984e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5818,+5.8189998699352145e+01,5820,39,1,+6.0216827392578125e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5819,+5.8199998699128628e+01,5821,39,1,+6.0347423553466797e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5820,+5.8209998698905110e+01,5822,39,1,+6.0478023529052734e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5821,+5.8219998698681593e+01,5823,39,1,+6.0608634948730469e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5822,+5.8229998698458076e+01,5824,39,1,+6.0739253997802734e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5823,+5.8239998698234558e+01,5825,39,1,+6.0869876861572266e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5824,+5.8249998698011041e+01,5826,39,1,+6.1000511169433594e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5825,+5.8259998697787523e+01,5827,39,1,+6.1131156921386719e+01,+3.1967477426183893e+02,-1.3156363708248011e+00,+0.0000000000000000e+00,-4.5266817323863506e-03,+0.0000000000000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
rows = df20.shape[0]
num_del = rows%100
df20.drop(labels=range(rows-num_del, rows), axis=0, inplace=True)
df20.shape

(5800, 45)

In [6]:
"""
Other constants which must be defined after reading in df.


Note: when determing number of objs, we use (#cols-2)/PATTERN.
    But quite often, the raw data has an empty column in the end,
    with pandas automatically giving a name "Unnamed.0"
"""
# C
while (len(df20.columns)-2)%PATTERN != 0:
    # del that col
    print("Found an empty col at the end")
    df20.drop(df20.columns[-1], axis=1, inplace=True)
    
    
NUM_OBJS = (len(df20.columns)-2)//PATTERN
BEGIN_IDX = NUM_OBJS # current df has 10 roadlines, 0-9
TARGET = 10 # we want 14
END_IDX = 10

# Check if it is a whole number
NUM_OBJS

Found an empty col at the end

2

In [7]:
"""### Keep those cols we want and check ###"""

# a list of column names to delete
cols_to_del = [name for i, name in enumerate(df20.columns) if i%PATTERN not in index_to_keep and i!=1]
df20 = df20.drop(columns=cols_to_del)

df20.head(10)

,temp.1,temp.2,temp.4,temp.16,temp.23,temp.25,temp.37
0,2,38,+8.4193824768066406e+01,+3.5000000000000000e+00,NaN,NaN,NaN
1,3,38,+8.4193824768066406e+01,+3.5000000000000000e+00,NaN,NaN,NaN
2,4,38,+8.4193824768066406e+01,+3.5000000000000000e+00,NaN,NaN,NaN
3,5,38,+8.4193824768066406e+01,+3.5000000000000000e+00,NaN,NaN,NaN
4,6,38,+8.4193832397460938e+01,+3.5000000000000000e+00,NaN,NaN,NaN
5,7,38,+8.4193832397460938e+01,+3.5000000000000000e+00,NaN,NaN,NaN
6,8,38,+8.4193840026855469e+01,+3.5000000000000000e+00,NaN,NaN,NaN
7,9,38,+8.4193840026855469e+01,+3.5000000000000000e+00,NaN,NaN,NaN
8,10,38,+8.4193847656250000e+01,+3.5000000000000000e+00,NaN,NaN,NaN
9,11,38,+8.4193847656250000e+01,+3.5000000000000000e+00,NaN,NaN,NaN

In [8]:
"""### do some simple pre-process and check ###"""
df20.fillna(PLACE_HOLDER, inplace=True)
df20.rename(columns={"temp.1":"simFrame"}, inplace=True)
df20.set_index("simFrame", inplace=True)
df20 = df20[~df20.index.duplicated(keep='first')]

"""
# rename col names of first chunk: id to id.0
rename_dict = {name:name+'.0' for name in col_of_one}
df20.rename(columns=rename_dict, inplace=True)

# rename type.x to obj_type.x to distinguish (pkg 7 roadmark also has type)
type_dict = {"type.{}".format(i): "obj_type.{}".format(i) for i in range(NUM_OBJS)}
df20.rename(columns=type_dict, inplace=True)
"""
new_names = ["{}.{}".format(name,i) for i in range(NUM_OBJS) for name in col_of_one]
df20.columns = new_names


print(df20.shape)
df20.head(10)

(5800, 6)

,signId.0,roadDist.0,value.0,signId.1,roadDist.1,value.1
simFrame,,,,,,
2,38,+8.4193824768066406e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
3,38,+8.4193824768066406e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
4,38,+8.4193824768066406e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
5,38,+8.4193824768066406e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
6,38,+8.4193832397460938e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
7,38,+8.4193832397460938e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
8,38,+8.4193840026855469e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
9,38,+8.4193840026855469e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
10,38,+8.4193847656250000e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99
11,38,+8.4193847656250000e+01,+3.5000000000000000e+00,-99.99,-99.99,-99.99

In [9]:
if list(df20.columns):
    print("HAVE")

HAVE

In [10]:
# Prepare, define in B
id_col = []
roadDist_col = []
value_col = []
row_num = df20.shape[0]    # Should be 4664 this time

if not list(df20.columns):
    # For pkg 20, there could be no valid data at all (empty df with no cols)
    print("Got an empty df")
    id_col = [PLACE_HOLDER]*row_num
    roadDist_col = [PLACE_HOLDER]*row_num
    value_col = [PLACE_HOLDER]*row_num
    
    
else:
    got = False
    # Start to loop
    for row in range(row_num):
        this_row = df20.iloc[row]
        got = False
        for i in range(NUM_OBJS):
            if this_row["signId.{}".format(i)] == 0:
                id_col.append(this_row["signId.{}".format(i)])
                roadDist_col.append(this_row["roadDist.{}".format(i)])
                value_col.append(this_row["value.{}".format(i)])
                got = True
                break
        if not got:
            # Strange thing found: some rows (<100 out of 8000+) have no data of ego car
            id_col.append(PLACE_HOLDER)
            roadDist_col.append(PLACE_HOLDER)
            value_col.append(PLACE_HOLDER)
            # print("row num: ", row)

    # IMPORTANT: since each row must have ego car data, they should match
    print(len(roadDist_col), len(value_col), row_num, len(id_col))

5800 5800 5800 5800

In [11]:
df20_new = pd.DataFrame({
    'simFrame': df20.index,
    "signId": id_col,
    "roadDist": roadDist_col,
    "value": value_col
})
df20_new.set_index('simFrame', inplace=True)
df20_new

                         signId  roadDist  value
simFrame
                      2  -99.99    -99.99 -99.99
                      3  -99.99    -99.99 -99.99
                      4  -99.99    -99.99 -99.99
                      5  -99.99    -99.99 -99.99
                      6  -99.99    -99.99 -99.99
                      7  -99.99    -99.99 -99.99
                      8  -99.99    -99.99 -99.99
                      9  -99.99    -99.99 -99.99
                     10  -99.99    -99.99 -99.99
                     11  -99.99    -99.99 -99.99
                     12  -99.99    -99.99 -99.99
                     13  -99.99    -99.99 -99.99
                     14  -99.99    -99.99 -99.99
                     15  -99.99    -99.99 -99.99
                     16  -99.99    -99.99 -99.99
                     17  -99.99    -99.99 -99.99
                     18  -99.99    -99.99 -99.99
                     19  -99.99    -99.99 -99.99
                     20  -99.99    -99.99 -99.99
                     21  -99.99    -99.99 -99.99
                     22  -99.99    -99.99 -99.99
                     23  -99.99    -99.99 -99.99
                     24  -99.99    -99.99 -99.99
                     25  -99.99    -99.99 -99.99
                     26  -99.99    -99.99 -99.99
                     27  -99.99    -99.99 -99.99
                     28  -99.99    -99.99 -99.99
                     29  -99.99    -99.99 -99.99
                     30  -99.99    -99.99 -99.99
                     31  -99.99    -99.99 -99.99
...                         ...       ...    ...
                   5772  -99.99    -99.99 -99.99
                   5773  -99.99    -99.99 -99.99
                   5774  -99.99    -99.99 -99.99
                   5775  -99.99    -99.99 -99.99
                   5776  -99.99    -99.99 -99.99
                   5777  -99.99    -99.99 -99.99
                   5778  -99.99    -99.99 -99.99
                   5779  -99.99    -99.99 -99.99
                   5780  -99.99    -99.99 -99.99
                   5781  -99.99    -99.99 -99.99
                   5782  -99.99    -99.99 -99.99
                   5783  -99.99    -99.99 -99.99
                   5784  -99.99    -99.99 -99.99
                   5785  -99.99    -99.99 -99.99
                   5786  -99.99    -99.99 -99.99
                   5787  -99.99    -99.99 -99.99
                   5788  -99.99    -99.99 -99.99
                   5789  -99.99    -99.99 -99.99
                   5790  -99.99    -99.99 -99.99
                   5791  -99.99    -99.99 -99.99
                   5792  -99.99    -99.99 -99.99
                   5793  -99.99    -99.99 -99.99
                   5794  -99.99    -99.99 -99.99
                   5795  -99.99    -99.99 -99.99
                   5796  -99.99    -99.99 -99.99
                   5797  -99.99    -99.99 -99.99
                   5798  -99.99    -99.99 -99.99
                   5799  -99.99    -99.99 -99.99
                   5800  -99.99    -99.99 -99.99
                   5801  -99.99    -99.99 -99.99

[5800 rows x 3 columns]

In [12]:
# do the check after the sort, there should be no output if it's correct
assert len(df20_new["signId"].value_counts()) <=2, "still has id other than 0 and place_holder"

In [13]:
df20_new.to_csv(OUTPUT_PATH)